# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Add nuget source
      run: dotnet nuget add source --username bricefourie --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/bricefourie/index.json"
    - name: Publish Package
      run: dotnet nuget push "ConvertHeroLibrary/bin/Release/ConvertHero.Core.1.0.0.nupkg"  --api-key ${{ secrets.MY_GITHUB_PAT }} --source "github"
