# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0
      with:
       nuget-version: # optional, default is latest
       nuget-api-key: ${{ secrets.GITHUB_TOKEN }}
       nuget-api-key-source: https://nuget.pkg.github.com/bricefourie/index.json
